version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: service:db
    restart: unless-stopped

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
